# Generated by Django 5.2.4 on 2025-08-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cat_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="category name"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "cat_image",
                    models.ImageField(
                        upload_to="upload/categories", verbose_name="category image"
                    ),
                ),
            ],
        ),
    ]
