# Generated by Django 5.2.4 on 2025-08-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_cat_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
    ]
