# Generated by Django 5.2.4 on 2025-08-02 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0002_alter_category_cat_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pro_name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="product name"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("descriptions", models.TextField(verbose_name="descriptions")),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="discount price",
                    ),
                ),
                (
                    "regular_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="regular price"
                    ),
                ),
                (
                    "pro_image",
                    models.ImageField(
                        upload_to="products", verbose_name="product image"
                    ),
                ),
                ("stock", models.IntegerField(verbose_name="stack")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="is available"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modify_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                        verbose_name="category",
                    ),
                ),
            ],
        ),
    ]
