# Generated by Django 5.2.4 on 2025-08-05 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variation_category",
                    models.CharField(
                        choices=[("color", "color"), ("size", "size")],
                        max_length=100,
                        verbose_name="variation category",
                    ),
                ),
                (
                    "variation_value",
                    models.CharField(max_length=100, verbose_name="variation value"),
                ),
                ("is_active", models.BooleanField(verbose_name="is_active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stores.product",
                        verbose_name="product",
                    ),
                ),
            ],
        ),
    ]
