# Generated by Django 5.2.4 on 2025-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is_active"),
        ),
    ]
