# Generated by Django 5.2.4 on 2025-08-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="price"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="date_added",
            field=models.DateField(auto_now_add=True, verbose_name="added at"),
        ),
    ]
