# Generated by Django 5.2.4 on 2025-08-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_cartitem_price_alter_cart_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="price"
            ),
        ),
    ]
