# Generated by Django 5.2.4 on 2025-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_alter_cartitem_price"),
        ("stores", "0003_alter_variation_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(
                to="stores.variation", verbose_name="Variation"
            ),
        ),
    ]
