# Generated by Django 5.2.4 on 2025-08-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "username",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="username"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="phone"
                    ),
                ),
                (
                    "date_join",
                    models.DateTimeField(auto_now_add=True, verbose_name="join at"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now_add=True, verbose_name="join at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="is_active"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="is_active"),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="is_active"),
                ),
                (
                    "is_superadmin",
                    models.BooleanField(default=False, verbose_name="is_active"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
