# Generated by Django 5.2.4 on 2025-08-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountnew",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="is_admin"),
        ),
        migrations.AlterField(
            model_name="accountnew",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="is_staff"),
        ),
        migrations.AlterField(
            model_name="accountnew",
            name="is_superadmin",
            field=models.BooleanField(default=False, verbose_name="is_superadmin"),
        ),
    ]
