# Generated by Django 5.2.4 on 2025-08-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_accountnew_is_admin_alter_accountnew_is_staff_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountnew",
            options={"verbose_name": "Account", "verbose_name_plural": "Accounts"},
        ),
    ]
