# Generated by Django 5.2.4 on 2025-08-16 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountnew_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=150, verbose_name='address 1')),
                ('address_line_2', models.CharField(blank=True, max_length=150, verbose_name='address 2')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='state')),
                ('profile_pic', models.ImageField(blank=True, upload_to='userProfile', verbose_name='picture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
