# Generated by Django 5.2.4 on 2025-08-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default/user_default.png', upload_to='userProfile', verbose_name='picture'),
        ),
    ]
